src/accounts/urls.py
from django.urls import path

from accounts.views import (
    UserRegistrationView,
    UserLoginView,
    UserLogoutView,
    UserActivationView,
    UserDashboardView,
    UserForgotPassword, UserResetValidateView, UserResetPassword, UserDashboardOrdersView, UserDashboardChangeProfile,
    UserDashboardChangePassword, UserDashboardOrderDetails
)

app_name = 'accounts'

urlpatterns = [
    path('accounts/register/', UserRegistrationView.as_view(), name='register'),
    path('accounts/login/', UserLoginView.as_view(), name='login'),
    path('accounts/logout/', UserLogoutView.as_view(), name='logout'),
    
    path('accounts/dashboard/', UserDashboardView.as_view(), name='dashboard'),
    path('accounts/dashboard/orders/', UserDashboardOrdersView.as_view(), name='dashboard_orders'),
    path('accounts/dashboard/order/<int:pk>/details/', UserDashboardOrderDetails.as_view(), name='order_details'),
    path('accounts/dashboard/profile/', UserDashboardChangeProfile.as_view(), name='dashboard_profile'),
    path('accounts/dashboard/password/', UserDashboardChangePassword.as_view(), name='dashboard_password'),
    
    path('accounts/activate/<uidb64>/<token>', UserActivationView.as_view(), name='activation'),
    
    path('accounts/forgot_password/', UserForgotPassword.as_view(), name='forgot_password'),
    path('accounts/reset_password_validate/<uidb64>/<token>', UserResetValidateView.as_view(), name='reset_password_validate'),
    path('accounts/reset_password/', UserResetPassword.as_view(), name='reset_password'),
]

src/cart/urls.py
from django.urls import path

from cart.views import CartAddView, CartIndex, CartDeleteView, CartItemRemoveView, CheckoutView

app_name = 'cart'

urlpatterns = [
    path('cart/', CartIndex.as_view(), name='index'),
    path('cart/add/<int:id>', CartAddView.as_view(), name='add'),
    path('cart/reduce/<int:product_id>/<int:cart_item_id>', CartDeleteView.as_view(), name='reduce'),
    path('cart/remove/<int:id>', CartItemRemoveView.as_view(), name='remove'),
    path('cart/checkout/', CartIndex.as_view(template_name='checkout.html'), name="checkout")
]

src/ecommerce/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings
from .views import home

from django.contrib.auth import get_user_model, login
from django.http import HttpResponse


urlpatterns = [
        path('secure_admin/', admin.site.urls),
        path('', home, name='home'),
        path('', include('store.urls')),
        path('', include('cart.urls')),
        path('', include('accounts.urls')),
        path('', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/store/urls.py
from django.urls import path

from store.views import ProductsList, ProductDetails

app_name = 'store'

urlpatterns = [
    path('store/', ProductsList.as_view(), name='index'),
    path('store/category/<slug:slug>/', ProductsList.as_view(), name='index'),
    path('store/details/<slug:slug>/', ProductDetails.as_view(), name='product-details'),
    path('store/search/', ProductsList.as_view(), name='search'),
]

src/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from accounts.models import CustomUser, UserProfile


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'address', 'password1', 'password2']
    
    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        
        self.set_attrs('first_name', 'placeholder', 'Entrer votre prénom')
        self.set_attrs('last_name', 'placeholder', 'Entrer votre nom')
        self.set_attrs('email', 'placeholder', 'Entrer votre email')
        self.set_attrs('phone_number', 'placeholder', 'Entrer numéro (Ex: +226 72529678)')
        self.set_attrs('phone_number', 'required', True)
        self.set_attrs('address', 'placeholder', 'Entrer votre adresse')
        self.set_attrs('password1', 'placeholder', 'Mot de passe')
        self.set_attrs('password2', 'placeholder', 'Répéter votre mot de passe')
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    
    def set_attrs(self, field_name: str, attribute: str, value):
        """
        This method permit to set automatically an attribute with field_name, attribute_value and value
        """
        self.fields[field_name].widget.attrs[attribute] = value


class UserLoginForm(AuthenticationForm):
    username = forms.EmailField()
    
    class Meta:
        model = CustomUser
        fields = ['username', 'password']
    
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    
    def set_attrs(self, field_name: str, attribute: str, value):
        """
        This method permit to set automatically an attribute with field_name, attribute_value and value
        """
        self.fields[field_name].widget.attrs[attribute] = value


class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(
        max_length=155,
        widget=forms.TextInput({
            'class': 'form-control',
            'placeholder': 'Entrez votre e-mail',
            'required': True
        })
    )


class ResetPasswordForm(forms.Form):
    password = forms.CharField(
        max_length=155,
        widget=forms.PasswordInput({
            'class': 'form-control',
            'placeholder': 'Veuillez entrer un nouveau mot de passe',
        })
    )
    confirm_password = forms.CharField(
        max_length=155,
        widget=forms.PasswordInput({
            'class': 'form-control',
            'placeholder': 'Veuillez confirmer votre mot de passe',
        })
    )


class UserProfileForm(forms.ModelForm):
    picture = forms.ImageField(widget=(forms.FileInput(attrs={})), error_messages={
        'invalid': 'Veuillez entrez uniquement une image',
        'required': 'L\'image est requise'
    })
    
    class Meta:
        fields = ['country', 'city', 'quartier', 'picture']
        model = UserProfile

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
    
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class UserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'phone_number', 'address']
    
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

src/accounts/views.py
import os

from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.shortcuts import redirect, get_object_or_404

# Create your views here.
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import FormView, TemplateView, ListView, UpdateView, DetailView

from accounts.forms import UserRegistrationForm, UserLoginForm, ForgotPasswordForm, ResetPasswordForm, UserForm, \
    UserProfileForm
from utils.mixins import CustomLoginRequiredMixin
from accounts.models import CustomUser, UserProfile
from ecommerce import settings
from orders.models import Order, OrderProduct


class UserRegistrationView(FormView):
    template_name = 'register.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('store:index')
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password1'])
        email = form.cleaned_data['email']
        user.save()
        UserProfile.objects.create(user=user)
        
        super(UserRegistrationView, self).form_valid(form)
        
        self.send_activation_email(user)
        
        return redirect(reverse('accounts:login') + f'?command=verification&email=' + email)
    
    def send_activation_email(self, user: CustomUser) -> None:
        """
        This function permit to send a validation e-mail to user
        """
        
        token = default_token_generator.make_token(user=user)
        uid = urlsafe_base64_encode(str(user.pk).encode('utf-8'))
        
        domain = get_current_site(self.request).domain
        mail_subject = "Activation de votre compte"
        activation_link = f"http://{domain}{reverse('accounts:activation', kwargs={'uidb64': uid, 'token': token})}"
        
        message = render_to_string('email_validation.html', {
            'user': user,
            'activation_link': activation_link
        })
        
        send_mail(subject=mail_subject, message=message, html_message=message, from_email='elirameskongo1234@gmail.com',
                  recipient_list=[user.email])


class UserLoginView(LoginView):
    form_class = UserLoginForm
    template_name = 'login.html'
    
    def form_valid(self, form):
        messages.success(self.request, "Vous avez été connecté avec succès")
        return super().form_valid(form)
    
    def get_success_url(self):
        return self.request.POST.get('next') or reverse_lazy('accounts:dashboard')


class UserLogoutView(LogoutView):
    def dispatch(self, *args, **kwargs):
        messages.success(self.request, f"{self.request.user.first_name} a bien été déconnecté")
        return super(UserLogoutView, self).dispatch(*args, **kwargs)
    
    next_page = settings.LOGOUT_REDIRECT_URL


class UserActivationView(View):
    def get(self, *args, **kwargs):
        uidb64 = self.kwargs['uidb64']
        token = self.kwargs['token']
        
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = CustomUser.objects.get(id=uid)
        except(TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
            user = None
        
        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(self.request, 'Félicitations, votre compte a bien été vérifié.')
            return redirect('accounts:login')
        else:
            messages.error(self.request, "Le lien d'activation est invalide ou a expiré")
            return redirect('accounts:register')


class UserDashboardView(CustomLoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'
    login_url = reverse_lazy("accounts:login")
    
    def get_context_data(self, *args, **kwargs):
        context = super(UserDashboardView, self).get_context_data(*args, **kwargs)
        
        user_profile = get_object_or_404(UserProfile, user=self.request.user)
        
        order = Order.objects.filter(user=self.request.user).order_by('-created_at')
        counter_order = order.count()
        context['counter_order'] = counter_order
        context['user_profile'] = user_profile
        
        return context


class UserDashboardOrdersView(CustomLoginRequiredMixin, ListView):
    template_name = 'dashboard_orders.html'
    login_url = reverse_lazy("accounts:login")
    context_object_name = 'orders'
    model = Order
    
    def get_queryset(self, *args, **kwargs):
        related_orders = Order.objects.filter(user=self.request.user).order_by("-updated_at")
        
        return related_orders


class UserDashboardOrderDetails(DetailView):
    model = Order
    template_name = 'order_details.html'
    context_object_name = 'order'
    
    def get_context_data(self, *args,**kwargs):
        context = super(UserDashboardOrderDetails, self).get_context_data(*args, **kwargs)
        
        order = self.get_object()
        user = self.request.user
        total = order.total
        tax = order.tax
        sub_total = (order.total - order.tax)
        
        order_products = OrderProduct.objects.filter(user=user, order=order)
        
        context['order_products'] = order_products
        context['total'] = total
        context['tax'] = tax
        context['sub_total'] = sub_total
        
        return context

class UserDashboardChangeProfile(CustomLoginRequiredMixin, TemplateView):
    template_name = 'dashboard_profile.html'
    
    def post(self, *args, **kwargs):
        user_profile = get_object_or_404(UserProfile, user=self.request.user)
        user_form = UserForm(self.request.POST, instance=self.request.user)
        profile_form = UserProfileForm(self.request.POST, self.request.FILES, instance=user_profile)
        
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            
            if not self.request.FILES == {}:
                # Suppression de l'ancienne images en cas mise à jour de la photo de profile afin d'optimiser l'espace
                if profile_form.cleaned_data['picture'] and user_profile.picture:
                    print()
                    path = user_profile.picture.path
                    new_path = path.split('src')[0] + "src"
                    old_picture_path = new_path + str(user_profile.picture.url)
                    if os.path.exists(old_picture_path):
                        os.remove(old_picture_path)
            
            else:
                if user_profile.picture:
                    profile_form.cleaned_data['picture'] = user_profile.picture
            profile_form.save()
            messages.success(self.request, "Mise à jour réussi !")
            return redirect("accounts:dashboard_profile")
        
        return self.render_to_response(context={
            'user_form': user_form,
            'profile_form': profile_form,
            'user_profile': user_profile
        })
    
    def get_context_data(self, *args, **kwargs):
        user_profile = get_object_or_404(UserProfile, user=self.request.user)
        
        context = super(UserDashboardChangeProfile, self).get_context_data(*args, **kwargs)
        
        user_form = UserForm(instance=self.request.user)
        profile_form = UserProfileForm(instance=user_profile)
        
        if user_profile:
            context['user_profile'] = user_profile
        
        context['user_form'] = user_form
        context['profile_form'] = profile_form
        
        return context


class UserDashboardChangePassword(CustomLoginRequiredMixin, PasswordChangeView):
    form_class = PasswordChangeForm
    template_name = 'dashboard_change_password.html'
    success_url = reverse_lazy("accounts:dashboard_password")
    
    def dispatch(self, *args, **kwargs):
        if self.request.method == 'POST' and self.get_form().is_valid():
            messages.success(self.request, "Votre mot de passe a bien été modifié")
        return super(UserDashboardChangePassword, self).dispatch(*args, **kwargs)


class UserForgotPassword(FormView):
    template_name = 'forgot_password.html'
    form_class = ForgotPasswordForm
    
    def form_valid(self, form):
        email = form.cleaned_data['email']
        
        if CustomUser.objects.filter(email=email).exists():
            user = CustomUser.objects.get(email__exact=email)
            self.request.session['uid'] = user.id
            self.send_reset_password_email(user)
            messages.success(
                self.request,
                f"Nous vous avons envoyé un e-mail({user.email}) pour la réinitialisation de votre mot de passe."
            )
            return redirect('accounts:forgot_password')
        else:
            messages.error(
                self.request,
                "Aucun utilisateur avec cet e-mail n'existe"
            )
            return redirect('accounts:forgot_password')
    
    def send_reset_password_email(self, user):
        """
        This method permit to send a reset password email to a specific user
        """
        token = default_token_generator.make_token(user)
        uidb64 = urlsafe_base64_encode(str(user.id).encode('utf-8'))
        
        domain_site = get_current_site(self.request).domain
        activation_link = f"http://{domain_site}/accounts/reset_password_validate/{uidb64}/{token}"
        
        mail_subject = 'Réinitialisation de votre de passe'
        
        message = render_to_string('reset_password_email.html', {
            'user': user,
            'activation_link': activation_link,

src/accounts/templates/dashboard.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<section class="section-conten padding-y bg">
    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
            <main class="col-md-9">
            {% include 'includes/messages.html' %}
                <article class="card">
                    <header class="card-header">
                        <strong class="d-inline-block mr-3">Connecté en tant que:</strong><span>{{ request.user.get_full_name }}</span>
                    </header>
                    <div class="card-body">
                        <div class="row">
                            <div class="card col-md-6">
                                <div class="card-body text-center">
                                    <h3>Total des commandes</h3>
                                        <h4>{{ counter_order }}</h4>
                                    {% if counter_order > 1 %}
                                        <a href="{% url 'accounts:dashboard_orders' %}">Voir les commandes</a>
                                    {% else %}
                                        <a href="{% url 'accounts:dashboard_orders' %}">Voir la commande</a>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="card col-md-6">
                                <div class="card-body text-center">
                                    {% if user_profile.picture %}
                                        <img src="{{ user_profile.picture.url }}" alt="Photo de profile" width="65px" height="auto" style="border-radius: 50%">
                                    {% else %}
                                        <img src="https://www.w3schools.com/howto/img_avatar.png" alt="Photo de profile de l'utilisateur" width="75" style="border-radius: 50%">
                                    {% endif %}
                                    <a href="{% url 'accounts:dashboard_profile' %}"><p class="my-2">{{ request.user.email }}</p></a>
                                    <p>{{ request.user.phone_number }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </article>
            </main>
        </div>
    </div>
</section>
{% endblock %}

src/accounts/templates/dashboard_change_password.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
            <main class="col-md-9">
            {% include 'includes/messages.html' %}
            {% if form.errors %}
                <div class="mx-auto container">
                    <div class="alert alert-danger">
                        <strong class="mb-3 d-block">Veuillez corriger les erreurs suivantes :</strong>
                        <ul>
                            {% for field, errors in form.errors.items %}
                                {% for error in errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endif %}
                <article class="card">
                    <header class="card-header">
                        <h4><strong class="d-inline-block mr-3">Modifier le mot de passe</strong></h4>
                    </header>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <form action="{% url 'accounts:dashboard_password' %}" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-row col-md-12">
                                        <div class="form-group col-md-12">
                                            <label>Mot de passe</label>
                                            {{ form.old_password|add_class:"form-control" }}
                                        </div>
                                        <div class="form-group col-md-12">
                                            <label>Nouveau mot de passe</label>
                                            {{ form.new_password1|add_class:"form-control" }}
                                        </div>
                                        <div class="form-group col-md-12">
                                            <label>Confirmez le nouveau mot de passe</label>
                                            {{ form.new_password2|add_class:"form-control" }}
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-primary ml-2">Soumettre</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </article>
            </main>
        </div>
    </div>
</section>
{% endblock %}

src/accounts/templates/dashboard_orders.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}

{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
            <main class="col-md-9">
                {% if orders %}
                <article class="card">
                    <header class="card-header">
                        <h5><strong class="d-inline-block mr-3">Votre historique de commande</strong></h5>
                    </header>
                    <div class="card-body">
                        <div class="row">
                            <table class="table table-hover">
                              <thead>
                                <tr>
                                  <th scope="col">N° de la commande</th>
                                  <th scope="col">Infos</th>
                                  <th scope="col">Total de la commande</th>
                                  <th scope="col">Date</th>
                                </tr>
                              </thead>
                              <tbody>
                              {% for order in orders %}
                                    <tr>
                                      <th scope="row"><a href="{% url 'accounts:order_details' pk=order.id %}">#{{ order.order_number }}</a></th>
                                      <td>{{ order.full_name }}</td>
                                      <td class="text-center">{{ order.total|intcomma }} $</td>
                                      <td>{{ order.updated_at }}</td>
                                    </tr>
                              {% endfor %}
                              </tbody>
                            </table>
                        </div>
                    </div>
                </article>
                {% else %}
                    <div class="text-center">
                    <h2>Vous n'avez auncune commande pour l'instant</h2>
                        <a href="{% url 'store:index' %}" class="btn btn-secondary">Visitez la boutique</a>
                    </div>
                {% endif %}
            </main>
        </div>
    </div>
</section>
{% endblock %}

src/accounts/templates/dashboard_profile.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
        <div class="row">
            {% include 'includes/dashboard_sidebar.html' %}
            <main class="col-md-9">
            {% include 'includes/messages.html' %}
            {% if user_form.errors %}
                <div class="mx-auto container">
                    <div class="alert alert-danger">
                        <strong class="mb-3 d-block">Veuillez corriger les erreurs suivantes :</strong>
                        <ul>
                            {% for field, errors in user_form.errors.items %}
                                {% for error in errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endif %}
            {% if profile_form.errors %}
                <div class="mx-auto container">
                    <div class="alert alert-danger">
                        <strong class="mb-3 d-block">Veuillez corriger les erreurs suivantes :</strong>
                        <ul>
                            {% for field, errors in profile_form.errors.items %}
                                {% for error in errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endif %}
                <article class="card">
                    <header class="card-header d-flex justify-content-between align-items-center">
                        <h4><strong class="d-inline-block mr-3">Votre profile</strong></h4>
                        {% if user_profile.picture %}
                            <img src="{{ user_profile.picture.url }}" alt="Photo de profile" width="65px" height="65px" style="border-radius: 50%">
                        {% else %}
                            <img src="https://www.w3schools.com/howto/img_avatar.png" alt="Photo de profile de l'utilisateur" width="75" style="border-radius: 50%">
                        {% endif %}
                    </header>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <form action="{% url 'accounts:dashboard_profile' %}" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-row col-md-12">
                                        <div class="form-group col-md-6">
                                            <label>Prénom</label>
                                            {{ user_form.first_name }}
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>Nom</label>
                                            {{ user_form.last_name }}
                                        </div>
                                    </div>
                                    <div class="form-row col-md-12">
                                        <div class="form-group col-md-12">
                                            <label>Photo de profile</label>
                                            {{ profile_form.picture }}
                                        </div>
                                    </div>
                                    <div class="form-row col-md-12">
                                        <div class="form-group col-md-6">
                                            <label>Numéro de téléphone</label>
                                            {{ user_form.phone_number }}
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>Adresse</label>
                                            {{ user_form.address }}
                                        </div>
                                    </div>
                                    <div class="form-row col-md-12">
                                        <div class="form-group col-md-4">
                                            <label>Pays</label>
                                            {{ profile_form.country }}
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>Ville</label>
                                            {{ profile_form.city }}
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label>Quartier</label>
                                            {{ profile_form.quartier }}
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-primary ml-2">Soumettre</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </article>
            </main>
        </div>
    </div>
</section>
{% endblock %}

src/accounts/templates/email_validation.html
{% autoescape off %}
    <h1 class="text-info">Bonjour {{ user.get_full_name }},</h1>
    <h4>Veuillez cliquer sur le lien ci-dessous pour activer votre compte :</h4>
    <a href="{{ activation_link }}">Activer mon compte</a>

    <h4>Si vous n'êtes pas concerné par cela, ignoré juste ce message</h4>

{% endautoescape %}

src/accounts/templates/reset_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <section class="section-content padding-y" style="min-height:84vh">

        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
            {% include 'includes/messages.html' %}
          <h4 class="card-title my-4">Mot de passe oublié</h4>
          <form method="post" action="{% url 'accounts:reset_password' %}">
              {% csrf_token %}
              <div class="form-group">
                  <label>Mot de passe</label>
                  {{ form.password }}
              </div>
              <div class="form-group">
                  <label>Confirmation du mot de passe</label>
                  {{ form.confirm_password }}
              </div>
              <div class="form-group">
                  <button type="submit" class="btn btn-primary">Soumettre</button>
                  <button type="reset" class="btn btn-secondary">Annuler</button>
              </div>
          </form>
          </div>
        </div>
         <p class="text-center mt-4">Mot de passe retrouvé ?<a href="{% url 'accounts:login' %}"> Connectez-vous</a></p>
         <br><br>
    </section>
{% endblock %}