src/cart/urls.py
from django.urls import path

from cart.views import CartAddView, CartIndex, CartDeleteView, CartItemRemoveView, CheckoutView

app_name = 'cart'

urlpatterns = [
    path('cart/', CartIndex.as_view(), name='index'),
    path('cart/add/<int:id>', CartAddView.as_view(), name='add'),
    path('cart/reduce/<int:product_id>/<int:cart_item_id>', CartDeleteView.as_view(), name='reduce'),
    path('cart/remove/<int:id>', CartItemRemoveView.as_view(), name='remove'),
    path('cart/checkout/', CartIndex.as_view(template_name='checkout.html'), name="checkout")
]

src/ecommerce/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings
from .views import home

from django.contrib.auth import get_user_model, login
from django.http import HttpResponse


urlpatterns = [
        path('secure_admin/', admin.site.urls),
        path('', home, name='home'),
        path('', include('store.urls')),
        path('', include('cart.urls')),
        path('', include('accounts.urls')),
        path('', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/urls.py
from django.urls import path

from orders.views import PlaceOrder, OrderPayments, OrderComplete, OrderUpdate, OrderCancel

app_name = 'orders'

urlpatterns = [
    path('order/placeorder/', PlaceOrder.as_view(), name='placeorder'),
    path('order/payments/', OrderPayments.as_view(), name='payments'),
    path('order/update/<int:pk>', OrderUpdate.as_view(), name='update'),
    path('order/complete/', OrderComplete.as_view(), name='complete'),
    path('order/cancel/<int:pk>', OrderCancel.as_view(), name='cancel'),
]

src/store/urls.py
from django.urls import path

from store.views import ProductsList, ProductDetails

app_name = 'store'

urlpatterns = [
    path('store/', ProductsList.as_view(), name='index'),
    path('store/category/<slug:slug>/', ProductsList.as_view(), name='index'),
    path('store/details/<slug:slug>/', ProductDetails.as_view(), name='product-details'),
    path('store/search/', ProductsList.as_view(), name='search'),
]

src/cart/models.py
from django.db import models

# Create your models here.
from accounts.models import CustomUser
from store.models import Products, ProductVariations


class Cart(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Utilisateur', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Panier de {self.user}"
    
    class Meta:
        verbose_name = 'Panier'


class CartItem(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='Produit',)
    variations = models.ManyToManyField(ProductVariations, related_name='variations')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, verbose_name='Panier', related_name='items')
    quantity = models.IntegerField(verbose_name='Quantité', default=1)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return f"Produits du {self.cart}"
    
    @property
    def sub_total(self):
        return self.product.promotion_price * self.quantity
    
    class Meta:
        verbose_name = 'Elément du panier'
        verbose_name_plural = 'Eléments du panier'

src/cart/views.py
# Create your views here.
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, FormView

from accounts.models import UserProfile
from cart.models import Cart, CartItem
from orders.forms import OrderForm
from store.models import Products, ProductVariations


class CartAddView(LoginRequiredMixin, View):
    login_url = reverse_lazy('accounts:login')
    
    def post(self, request, *args, **kwargs):
        product = get_object_or_404(Products, id=self.kwargs['id'])
        
        # Ajout des différentes variations au produits
        product_variations = []
        for item in self.request.POST:
            key = item
            value = self.request.POST.get(key)
            if key != 'csrfmiddlewaretoken':
                try:
                    variation = ProductVariations.objects.filter(category__iexact=key, value__iexact=value).first()
                    if variation:
                        product_variations.append(variation)
                except:
                    pass
        
        cart, created = Cart.objects.get_or_create(user=self.request.user)
        
        # Vérifie si l'élément existe
        cart_item_exist = CartItem.objects.filter(product=product, cart=cart).exists()
        
        if cart_item_exist:
            cart_items = CartItem.objects.filter(product=product, cart=cart)
            
            exist_variations_list = []
            ids = []
            
            for item in cart_items:
                item_variations = item.variations.all()
                exist_variations_list.append(list(item_variations))
                ids.append(item.id)
            
            if product_variations in exist_variations_list:
                index = exist_variations_list.index(product_variations)
                item_id = ids[index]
                item = CartItem.objects.get(product=product, cart=cart, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, cart=cart)
                item.variations.set(product_variations)
                item.save()
        else:
            if product_variations:
                cart_item = CartItem.objects.create(product=product, cart=cart)
                cart_item.variations.set(product_variations)
                cart_item.save()
        
        return redirect('cart:index')

    """
        La surcharge de cette méthode permet d'afficher un message d'erreur à l'utilisateur lorsqu'il n'a pas les
        permission nécéssaire
    """

    def handle_no_permission(self):
        messages.error(self.request, "Vous devez être connecté pour effectuer cette action")
        return redirect(self.login_url)


class CartDeleteView(View):
    
    def post(self, request, *args, **kwargs):
        product = get_object_or_404(Products, id=self.kwargs['product_id'])
        item_id = self.kwargs['cart_item_id']
        
        cart = Cart.objects.get(user=self.request.user)
        if cart:
            cart_item = CartItem.objects.get(product=product, cart=cart, id=item_id)
            
            if cart_item and cart_item.quantity > 1:
                cart_item.quantity -= 1
                cart_item.save()
            else:
                cart_item.delete()
        else:
            messages.error(self.request, "Vous n'avez pas de panier")
        
        return redirect('cart:index')


class CartIndex(LoginRequiredMixin, TemplateView, FormView):
    template_name = 'cart.html'
    login_url = reverse_lazy('accounts:login')
    redirect_field_name = 'next'
    form_class = OrderForm
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        cart, created = Cart.objects.get_or_create(user=self.request.user)
        
        cart_items = cart.items.all()
        
        total_w_tax = 0
        for item in cart_items:
            total_w_tax += (item.quantity * item.product.promotion_price)
        
        tax = ((total_w_tax * 2) / 100)
        total = total_w_tax + tax
        context['items'] = cart_items
        context['total_w_tax'] = total_w_tax
        context['tax'] = tax
        context['total'] = total
        
        return context
    
    """
        La surcharge de cette méthode permet de présélectionner les différents champs que l'utilisateur a déjà rempli
        au niveau de son profil d'utilisateur
    """
    
    def get_form(self, form_class=OrderForm):
        user_profile = get_object_or_404(UserProfile, user=self.request.user)
        
        return OrderForm(instance=user_profile)

    """
        La surcharge de cette méthode permet d'afficher un message d'erreur à l'utilisateur lorsqu'il n'a pas les
        permission nécéssaire
    """

    def handle_no_permission(self):
        messages.error(self.request, "Vous devez être connecté pour accéder à cette page")
        return super(CartIndex, self).handle_no_permission()


class CartItemRemoveView(View):
    
    def post(self, *args, **kwargs):
        item = get_object_or_404(CartItem, id=int(self.kwargs['id']))
        if item:
            product_name = item.product.name
            item.delete()
            messages.success(self.request, f"Le produit {product_name} à bien été supprimer")
        
        return redirect('cart:index')


class CheckoutView(TemplateView):
    template_name = "checkout.html"

src/cart/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% load custom_filters %}
{% load humanize %}

{% block content %}
<section class="section-content padding-y bg">
<div class="container">
{% include 'includes/messages.html' %}
{% if not items %}
        <div class="text-center">
            <h2 class="mb-5">Votre Panier est vide</h2>
            <a href="{% url 'store:index' %}" class="btn btn-primary">Retournez faire des achats</a>
        </div>
{% else %}
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Produits</th>
  <th scope="col" width="120">Quantité</th>
  <th scope="col" width="120">Prix</th>
  <th scope="col" class="text-right" width="200">Action</th>
</tr>
</thead>
<tbody>
{% for item in items %}
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{ item.product.image.url }}" class="img-sm"></div>
			<figcaption class="info">
                <h5><a href="{% url 'store:product-details' slug=item.product.slug%}" class="title text-dark">{{ item.product.name }}</a></h5>
                <p class="text-muted">
                    {% for variation in item.variations.all %}
                        <strong>{{ variation.category | capfirst }}</strong>: {{ variation.value |capfirst }}<br>
                    {% endfor %}
                </p>
			</figcaption>
		</figure>
	</td>
	<td>
		<!-- col.// -->
					<div class="col">
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
                                <form action="{% url 'cart:reduce' product_id=item.product.id cart_item_id=item.id %}" method="post">
                                    {% csrf_token %}
							        <button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-minus"></i> </button>
                                </form>
							</div>
							<input type="text" class="form-control"  value="{{ item.quantity }}">
							<div class="input-group-append">
                                <form action="{% url 'cart:add' item.product.id %}" method="post">
                                    {% csrf_token %}
                                    {% for variation in item.variations.all %}
                                        <input type="hidden" name="{{ variation.category | lower }}" value="{{ variation.value | capfirst }}">
                                    {% endfor %}
							        <button class="btn btn-light" type="submit" id="button-plus" {% if item.quantity == item.product.stock %} disabled onmouseover="return confirm('Vous avez atteint la quantité maximale')" {% endif %} > <i class="fa fa-plus"></i> </button>
                                </form>
							</div>
						</div>
                    </div>
	</td>
	<td>
		<div class="price-wrap">
			<var class="price">${{ item.sub_total|intcomma }}</var>
			<small class="text-muted"> ${{ item.product.promotion_price|intcomma }} l'unité</small>
		</div>
	</td>
	<td class="text-right">
        <form action="{% url 'cart:remove' item.id %}" method="post">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cet élément de votre panier ?')">Supprimer</button>
        </form>
	</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>

	</aside>
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total</dt>
			  <dd class="text-right">${{ total_w_tax|intcomma }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Taxe:</dt>
			  <dd class="text-right"> ${{ tax|intcomma }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Prix total:</dt>
			  <dd class="text-right text-dark b"><strong>${{ total|intcomma}}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static './images/misc/payments.png' %}" height="26">
			</p>
			<a href="{% url 'cart:checkout' %}" class="btn btn-primary btn-block"> Paiement </a>
			<a href="{% url 'store:index' %}" class="btn btn-light btn-block">Continuer le shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->

{% endif %}

</div> <!-- row.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>

{% endblock %}

src/cart/templates/checkout.html
{% extends 'base.html' %}
{% load static %}

{% load custom_filters %}
{% load widget_tweaks  %}
{% load humanize %}

{% block content %}
<section class=" padding-y bg">
    <div class="container">
        {% include 'includes/messages.html' %}
        <div>
            <form action="{% url 'orders:placeorder' %}" class="row" method="post">
                {% csrf_token %}
                <aside class="col-lg-6 col-sm-8 mb-4">
                    <div class="card">
                        <div class="card-body">
                        <h4 class="card-title mb-4">Adresse de facturation</h4>
                            <div class="form-row">
                                <div class="form-group col-md-6 col-lg-6 col-sm-12">
                                    <label>Nom</label>
                                    {% render_field form.last_name value=request.user.last_name %}
                                </div>
                                <div class="form-group col-md-6 col-lg-6 col-sm-12">
                                    <label>Prénom</label>
                                    {% render_field form.first_name value=request.user.first_name %}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6 col-lg-6 col-sm-12">
                                    <label>E-mail</label>
                                    {% render_field form.email value=request.user.email %}
                                </div>
                                <div class="form-group col-md-6 col-lg-6 col-sm-12">
                                    <label>Numéro de téléphone</label>
                                    {% render_field form.phone_number value=request.user.phone_number %}
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Adresse</label>
                                    {% render_field form.address value=request.user.address %}
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-4 col-lg-4 col-sm-12">
                                    <label>Pays</label>
                                    {% render_field form.country value=request.user.profile.country %}
                                </div>
                                <div class="form-group col-md-4 col-lg-4 col-sm-12">
                                    <label>Ville</label>
                                    {% render_field form.city value=request.user.profile.city %}
                                </div>
                                <div class="form-group col-md-4 col-lg-4 col-sm-12">
                                    <label>Quartier</label>
                                    {% render_field form.quartier value=request.user.profile.quartier %}
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Un mot pour la commande</label>
                                {% render_field form.note rows=5 col=4 %}
                            </div>
                        </div>
                    </div>
                </aside>
                <aside class="col-lg-6 col-sm-8">
                    <div class="card">
                        <div class="card-body">
                            <table class="table table-borderless table-shopping-cart">
                                <thead class="text-muted">
                                <tr class="small text-uppercase">
                                  <th scope="col">Produits</th>
                                  <th scope="col" width="120">Quantité</th>
                                  <th scope="col" width="120">Prix</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for item in items %}
                                    <tr>
                                        <td>
                                            <figure class="itemside align-items-center">
                                                <div class="aside"><img src="{{ item.product.image.url }}" class="img-sm"></div>
                                                <figcaption class="info">
                                                    <p><a href="{% url 'store:product-details' slug=item.product.slug%}" class="title text-dark">{{ item.product.name }}</a></p>
                                                    <p class="text-muted small">
                                                        {% for variation in item.variations.all %}
                                                            <strong>{{ variation.category | capfirst }}</strong>: {{ variation.value |capfirst }}<br>
                                                        {% endfor %}
                                                    </p>
                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            <div class="text-center mt-3">
                                                <p>{{ item.quantity }} </p>
                                            </div>
                                        </td>
                                        <td class="text-left">
                                            <div class="price-wrap mt-3">
                                                <var class="price">${{ item.sub_total|intcomma }}</var>
                                                <small class="text-muted"> ${{ item.product.promotion_price|intcomma }} l'unité</small>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <button type="submit" class="btn btn-primary btn-block"> Commande </button>
                            <a href="{% url 'store:index' %}" class="btn btn-light btn-block">Continuer le shopping</a>
                        </div>
                    </div>
                </aside>
            </form>
        </div>
    </div>
</section>

{% endblock %}