src/cart/urls.py
from django.urls import path

from cart.views import CartAddView, CartIndex, CartDeleteView, CartItemRemoveView, CheckoutView

app_name = 'cart'

urlpatterns = [
    path('cart/', CartIndex.as_view(), name='index'),
    path('cart/add/<int:id>', CartAddView.as_view(), name='add'),
    path('cart/reduce/<int:product_id>/<int:cart_item_id>', CartDeleteView.as_view(), name='reduce'),
    path('cart/remove/<int:id>', CartItemRemoveView.as_view(), name='remove'),
    path('cart/checkout/', CartIndex.as_view(template_name='checkout.html'), name="checkout")
]

src/ecommerce/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings
from .views import home

from django.contrib.auth import get_user_model, login
from django.http import HttpResponse


urlpatterns = [
        path('secure_admin/', admin.site.urls),
        path('', home, name='home'),
        path('', include('store.urls')),
        path('', include('cart.urls')),
        path('', include('accounts.urls')),
        path('', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/urls.py
from django.urls import path

from orders.views import PlaceOrder, OrderPayments, OrderComplete, OrderUpdate, OrderCancel

app_name = 'orders'

urlpatterns = [
    path('order/placeorder/', PlaceOrder.as_view(), name='placeorder'),
    path('order/payments/', OrderPayments.as_view(), name='payments'),
    path('order/update/<int:pk>', OrderUpdate.as_view(), name='update'),
    path('order/complete/', OrderComplete.as_view(), name='complete'),
    path('order/cancel/<int:pk>', OrderCancel.as_view(), name='cancel'),
]

src/store/urls.py
from django.urls import path

from store.views import ProductsList, ProductDetails

app_name = 'store'

urlpatterns = [
    path('store/', ProductsList.as_view(), name='index'),
    path('store/category/<slug:slug>/', ProductsList.as_view(), name='index'),
    path('store/details/<slug:slug>/', ProductDetails.as_view(), name='product-details'),
    path('store/search/', ProductsList.as_view(), name='search'),
]

src/orders/models.py
from django.db import models

# Create your models here.
from phonenumber_field.modelfields import PhoneNumberField

from accounts.models import CustomUser
from store.models import Products, ProductVariations
from utils.constants import PAYMENT_METHODS, STATUS, COUNTRY_CHOICES, CITIES_CHOICES


class Payment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    method = models.CharField(choices=PAYMENT_METHODS, verbose_name='Méthodes de paiements', max_length=100)
    amount = models.FloatField(verbose_name='Montant')
    status = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Date de création')
    
    def __str__(self):
        return self.payment_id
    
    class Meta:
        verbose_name = 'Paiement'


class Order(models.Model):
    user = models.ForeignKey(CustomUser, models.CASCADE)
    payment = models.ForeignKey(Payment, models.SET_NULL, null=True)
    order_number = models.CharField(max_length=600, unique=True, verbose_name='Numéro de la commande')
    status = models.CharField(choices=STATUS, default='Nouveau', max_length=25)
    first_name = models.CharField(max_length=155, verbose_name='Prénom', blank=False, null=False)
    last_name = models.CharField(max_length=155, verbose_name='Nom', blank=False, null=False)
    email = models.EmailField(max_length=255, verbose_name='E-mail', blank=False, null=False)
    phone_number = PhoneNumberField(null=False, blank=False, error_messages={
        'invalid': 'Veuillez entrez un numéro de téléphone valide',
    })
    address = models.CharField(max_length=300, verbose_name='Adresse')
    country = models.CharField(choices=COUNTRY_CHOICES, verbose_name='Pays', max_length=75)
    city = models.CharField(choices=CITIES_CHOICES, verbose_name='Villes', max_length=75)
    quartier = models.CharField(max_length=100, blank=True)
    total = models.FloatField(null=False, blank=False)
    tax = models.FloatField(verbose_name='Taxe')
    note = models.TextField(verbose_name='Note pour la commande', max_length=250, blank=True)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Date de création')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Date de modification')
    
    def __str__(self):
        return f"Commande de {self.user.first_name}"
    
    def full_name(self):
        return f"{self.first_name} {str(self.last_name).upper()}"
    
    class Meta:
        verbose_name = 'Commande'


class OrderProduct(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=False, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE, null=True, blank=False)
    variation = models.ManyToManyField(ProductVariations,blank=False, related_name='order_products_variations')
    quantity = models.IntegerField(verbose_name='Quantité')
    product_price = models.FloatField(verbose_name='Prix du produit')
    is_ordered = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.product.name

src/orders/forms.py
from  django import  forms

from orders.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'address', 'country', 'city','quartier', 'note' ]

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
   
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        
        

src/orders/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import render, redirect

# Create your views here.
from django.template.loader import render_to_string

from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import FormView, TemplateView, UpdateView, DeleteView

from cart.models import Cart, CartItem
from orders.forms import OrderForm
from orders.models import Order, Payment, OrderProduct
from store.models import Products


def get_form_cleaned_data(param: str, form: OrderForm) -> str:
    """
        This function permit to get a value of a form_clean_data field
    """
    return form.cleaned_data[param]


class PlaceOrder(LoginRequiredMixin, TemplateView, FormView):
    login_url = reverse_lazy("accounts:login")
    form_class = OrderForm
    template_name = 'payments.html'
    success_url = reverse_lazy('accounts:login')
    
    def form_valid(self, form):
        
        last_name = get_form_cleaned_data('last_name', form)
        first_name = get_form_cleaned_data('first_name', form)
        phone_number = get_form_cleaned_data('phone_number', form)
        address = get_form_cleaned_data('address', form)
        country = get_form_cleaned_data('country', form)
        city = get_form_cleaned_data('city', form)
        quartier = get_form_cleaned_data('quartier', form)
        note = get_form_cleaned_data('note', form)
        email = form.cleaned_data['email']
        
        user = self.request.user
        if user:
            
            cart = Cart.objects.get(user=user)
            cart_items = cart.items.all()
            total_w_tax = 0
            for item in cart_items:
                total_w_tax += (item.quantity * item.product.promotion_price)
            
            tax = (total_w_tax * 2) / 100
            total = tax + total_w_tax
            
            order_number = str(int(datetime.now().timestamp())) + str(int(user.id))
            if email != user.email:
                messages.error(self.request, "Veuillez laissez la même adresse que celle de votre compte")
                return redirect('cart:checkout')
            elif phone_number != user.phone_number:
                messages.error(self.request, "Veuillez laissez le même numéro de téléphone que celui de votre compte")
                return redirect('cart:checkout')
            else:
                order = Order.objects.create(
                    user=user,
                    first_name=first_name,
                    email=email,
                    order_number=order_number,
                    last_name=last_name,
                    phone_number=phone_number,
                    address=address,
                    country=country,
                    city=city,
                    quartier=quartier,
                    note=note,
                    total=total,
                    tax=tax
                )
                
                messages.success(self.request, "Votre commande a bien été exécuté")
                self.request.session['order_number'] = order_number
                super(PlaceOrder, self).form_valid(form)
                
                return redirect("orders:payments")


class OrderUpdate(UpdateView):
    form_class = OrderForm
    template_name = 'order_update.html'
    model = Order
    success_url = reverse_lazy('orders:payments')
    
    def get_context_data(self, *args,**kwargs):
        context = super(OrderUpdate, self).get_context_data(*args, **kwargs)
        
        cart = Cart.objects.get(user=self.request.user)
        
        items = CartItem.objects.filter(cart=cart)
        context['items'] = items
        return context
 
    def form_valid(self, form):
        phone_number = get_form_cleaned_data('phone_number', form)
        email = form.cleaned_data['email']
    
        order = self.get_object()
    
        user = self.request.user
        if user:
            if email != user.email:
                messages.error(self.request, "Veuillez laissez la même adresse e-mail que celle de votre compte")
                return redirect(reverse('orders:update', args=[order.id]))
            elif phone_number != user.phone_number:
                messages.error(self.request, "Veuillez laissez le même numéro de téléphone que celui de votre compte")
                return redirect(reverse('orders:update', args=[order.id]))
            else:
                super(OrderUpdate, self).form_valid(form)
                messages.success(self.request, "Vos informations ont bien été mises à jour")
                return redirect(self.success_url)
        else:
            messages.error(self.request, "Veuillez vous connecté pour accéder à cette page")
            return redirect("accounts:login")
        
        
class OrderCancel(View):
    def post(self, *args, **kwargs):
        order_id = self.kwargs['pk']
        order = Order.objects.get(id=order_id)
        order.delete()
        self.request.session.delete('order_number')
        messages.success(self.request, "Votre commande a bien été annulé :(, veuillez poursuivre vos achats :)")
        return redirect("cart:index")
    
    
class OrderPayments(TemplateView):
    template_name = 'payments.html'

    def get_context_data(self, *args, **kwargs):
        context = super(OrderPayments, self).get_context_data(*args, **kwargs)
        
        cart = Cart.objects.get(user=self.request.user)
        cart_items = cart.items.all()
        order_number = self.request.session.get('order_number', None)
        if order_number:
            order = Order.objects.get(order_number=order_number)
            total_w_tax = order.total - order.tax
            
            context['order'] = order
            context['last_name'] = order.last_name
            context['total'] = order.total
            context['tax'] = order.tax
            context['first_name'] = order.first_name
            context['phone_number'] = order.phone_number
            context['email'] = order.email
            context['address'] = order.address
            context['country'] = order.country
            context['city'] = order.city
            context['quartier'] = order.quartier
            context['items'] = cart_items
            context['total_w_tax'] = total_w_tax
            
        return context
    
    def post(self, *args, **kwargs):
        order_number = self.request.session.get('order_number')
        if order_number:
            order = Order.objects.get(order_number=order_number)
            
            payment_id = str(int(datetime.now().timestamp()))
            
            # Stockage de la transaction en base de données
            payment = Payment(
                user=self.request.user,
                payment_id=payment_id,
                method='paytest',
                amount=order.total,
                status=True,
            )
            payment.save()
            
            order.payment = payment
            order.status = 'Accepté'
            order.is_ordered = True
            order.save()
            messages.success(self.request, "Votre commande a été finalisé avec succès")
            
            # Déplacement des éléments du panier en OrderProduct
            
            user = self.request.user
            cart = Cart.objects.get(user=user)
            cart_items = cart.items.all()
            for item in cart_items:
                order_product = OrderProduct(
                    user=user,
                    payment=payment,
                    order=order,
                    product=item.product,
                    quantity=item.quantity,
                    product_price=item.product.promotion_price,
                    is_ordered=True
                )
                order_product.save()
                order_product.variation.set(item.variations.all())
                order_product.save()
                # Réduire la quantité en stock du produit acheté
                
                product = Products.objects.get(
                    name=item.product.name,
                    created_at=item.product.created_at,
                )
                product.stock -= item.quantity
                product.save()
            
            # Suppression(Afin de vider) du panier de l'utilisateur (il sera recréé automatiquement)
            cart.delete()
            
            # Envoi d'un e-mail à l'acheteur pour lui confirmer sa commande
            
            message = render_to_string('order_email.html', {
                'user': self.request.user,
                'order_number': order_number
            })
            mail_subject = "Votre commande a bien été exécutée"
            
            send_mail(subject=mail_subject, message=message, html_message=message, from_email='elirameskongo1234@gmail.com', recipient_list=[self.request.user.email])
            
            return redirect("orders:complete")
        else:
            messages.error(self.request, "Vous n'avez pas accès à cette page")
            return redirect("cart:index")
        
   
class OrderComplete(TemplateView):
    template_name = 'order_complete.html'
    
    def get_context_data(self, *args, **kwargs):
        context = super(OrderComplete, self).get_context_data(*args, **kwargs)
        order_number = self.request.session.get('order_number', None)
        
        if order_number:
            order = Order.objects.get(order_number=order_number)
            order_products = OrderProduct.objects.filter(order=order)
            
            total = order.total
            tax = order.tax
            sub_total = (total - tax)
            
            context['order'] = order
            context['order_products'] = order_products
            context['total'] = total
            context['tax'] = tax
            context['sub_total'] = sub_total

src/orders/templates/order_complete.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}

{% block content %}
    <div class="container" style="margin-top: 50px;" onload="return confirm('Vous n\'aurez plus accès à cette page après l\'avoir quitté')">
        <center><i class="fas fa-check-circle" style="font-size: 72px;margin-bottom: 20px;color: #28A745;"></i></center>
        <h2 class="text-center">Payment réussi</h2>
        <br>
        <div class="text-center">
            <a href="{% url 'store:index' %}" class="btn btn-success d-inline-block mb-3">Poursuivre le shopping</a>
        {% include 'includes/messages.html' %}
        </div>
    </div>

    <div class="container" style="margin: 0 auto;width: 50%;padding: 50px;background: #f1f1f1;margin-top: 50px;margin-bottom: 50px;">
        <div class="row invoice row-printable">
            <div class="col-md-12">
                <div class="panel panel-default plain" id="dash_0">
                    <div class="panel-body p30">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="invoice-logo"><img src="{% static '/images/logo.png' %}" alt="Invoice logo" style="max-height: 40px;"></div>
                            </div>
                            <div class="col-lg-6">
                                <div class="invoice-from">
                                    <ul class="list-unstyled text-right">
                                        <li><strong>Facturé à</strong></li>
                                        <li>{{ order.first_name|capfirst }} {{ order.last_name|capfirst }}</li>
                                        <li>{{ order.country }}</li>
                                        <li>{{ order.city }}, {{ order.address }}</li>
                                        <li>{{ order.quartier }}</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="invoice-details mt25">
                                    <div class="well">
                                        <ul class="list-unstyled mb0">
                                            <li><strong>Commande</strong> #{{order.order_number}}</li>
                                            <li><strong>Transaction</strong> #{{ order.payment.payment_id }}</li>
                                            <li><strong>Date:</strong> {{ order.created_at|date:'d/m/Y à H:i:s' }}</li>
                                            <li><strong>Status:</strong> Payé</li>
                                        </ul>
                                    </div>
                                </div>

                                <div class="invoice-items">
                                    <div class="table-responsive" style="overflow: hidden; outline: none;" tabindex="0">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr>
                                                    <th class="per70 text-center">Produits</th>
                                                    <th class="per5 text-center">Qté</th>
                                                    <th class="per25 text-center">Total</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for order_product in order_products %}
                                                    <tr>
                                                        <td>
                                                            <h6>{{ order_product.product.name }}</h6>
                                                            <ul>
                                                                {% for variation in order_product.variation.all %}
                                                                    <li><strong>{{ variation.category | capfirst }}</strong>: {{ variation.value |capfirst }}<br></li>
                                                                {% endfor %}
                                                            </ul>
                                                        </td>
                                                        <td class="text-center">{{ order_product.quantity }}</td>
                                                        <td class="text-center">${{ order_product.product_price|intcomma}} USD</td>
                                                    </tr>
                                                {% endfor %}

                                            </tbody>
                                            <tfoot>
                                                <tr>
                                                    <th colspan="2" class="text-right">Sous total:</th>
                                                    <th class="text-center">${{ sub_total | intcomma }} USD</th>
                                                </tr>
                                                <tr>
                                                    <th colspan="2" class="text-right">Tax:</th>
                                                    <th class="text-center">${{ tax | intcomma }} USD</th>
                                                </tr>

                                                <tr>
                                                    <th colspan="2" class="text-right">Grand Total:</th>
                                                    <th class="text-center">${{ total | intcomma }} USD</th>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </div>
                                </div>
                                <div class="invoice-footer mt25">
                                    <p class="text-center">Merci et félicitations pour votre achat !!</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/orders/templates/order_email.html
{% autoescape off %}
    <h2>Salut {{ user.get_full_name }}, </h2>
    <h3>nous sommes heureux de vous faire savoir que votre commande à bien  été validé</h3>
    <p><strong>Numéro de la commande: </strong>{{ order_number }}</p>
    <p>Vous serez livré dans un délai de <strong>2 à 4 semaines</strong></p>
    <p>Cordialement, l'équique marketing de <strong>KONGO E-com Shop</strong></p>
{% endautoescape %}

src/orders/templates/payments.html
{% extends 'base.html' %}
{% load static %}

{% load custom_filters %}
{% load humanize %}

{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
        <h2 class="mb-5 text-center">Vérifier votre commandes et passer au paiement</h2>
        {% include 'includes/messages.html' %}
        <div class="row">
            <aside class="col-lg-9">
                <div class="card mb-2">
                    <h4 class="card-header">Adresse de facturation</h4>
                    <div class="card-body">
                        <p class="card-text"><strong>Nom: </strong>{{ last_name | capfirst }}</p>
                        <p class="card-text"><strong>Prénom: </strong>{{ first_name | capfirst }}</p>
                        <p class="card-text"><strong>Adresse: </strong>{{ address | capfirst }}</p>
                        <p class="card-text"><strong>Pays: </strong>{{ country | capfirst }}</p>
                        <p class="card-text"><strong>Ville: </strong>{{ city | capfirst }}</p>
                        <p class="card-text"><strong>Quartier: </strong>{{ quartier | capfirst }}</p>
                        <p class="card-text"><strong>E-mail: </strong>{{ email }}</p>
                        <p class="card-text"><strong>Numéro de téléphone: </strong>{{ phone_number }}</p>
                    </div>
                </div>
                <div class="card mb-2">
                    <h4 class="card-header">Méthode de paiement</h4>
                    <div class="card-body">
                        <p class="card-text">PayTest</p>
                    </div>
                </div>
                <div class="card mb-2">
                    <h4 class="card-header">Produits</h4>
                    <div class="card-body">
                        <aside class="col-lg-12 col-sm-8">
                            <table class="table table-borderless table-shopping-cart">
                                <thead class="text-muted">
                                <tr class="small text-uppercase">
                                  <th scope="col">Produits</th>
                                  <th scope="col" width="120">Quantité</th>
                                  <th scope="col" width="120">Prix</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for item in items %}
                                    <tr>
                                        <td>
                                            <figure class="itemside align-items-center">
                                                <div class="aside"><img src="{{ item.product.image.url }}" class="img-sm"></div>
                                                <figcaption class="info">
                                                    <p><a href="{% url 'store:product-details' slug=item.product.slug%}" class="title text-dark">{{ item.product.name }}</a></p>
                                                    <p class="text-muted small">
                                                        {% for variation in item.variations.all %}
                                                            <strong>{{ variation.category | capfirst }}</strong>: {{ variation.value |capfirst }}<br>
                                                        {% endfor %}
                                                    </p>
                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            <div class="text-center mt-3">
                                                <p>{{ item.quantity }} </p>
                                            </div>
                                        </td>
                                        <td class="text-left">
                                            <div class="price-wrap mt-3">
                                                <var class="price">${{ item.sub_total|intcomma }}</var>
                                                <small class="text-muted"> ${{ item.product.promotion_price|intcomma }} l'unité</small>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </aside>
                    </div>
                </div>
            </aside>
            <aside class="col-lg-3">
                <div class="card">
                    <div class="card-body">
                        <dl class="dlist-align">
                          <dt>Total</dt>
                          <dd class="text-right">${{ total_w_tax|intcomma }}</dd>
                        </dl>
                        <dl class="dlist-align">
                          <dt>Taxe:</dt>
                          <dd class="text-right"> ${{ tax|intcomma }}</dd>
                        </dl>
                        <dl class="dlist-align">
                          <dt>Prix total:</dt>
                          <dd class="text-right text-dark b"><strong>${{ total|intcomma}}</strong></dd>
                        </dl>
                        <hr>
                        <p class="text-center mb-3">
                            <img src="{% static './images/misc/payments.png' %}" height="26">
                        </p>
                        <form action="{% url 'orders:payments' %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-secondary btn-block">PayTest</button>
                        </form>
                    </div>
                </div>
                <div class="card my-3">
                    <div class="card-body">
                        <a href="{% url 'orders:update' pk=order.id %}" class="btn btn-primary btn-block">Modifier vos informations</a>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <form action="{% url 'orders:cancel' pk=order.id %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-danger btn-block">Annuler la commande</button>
                        </form>
                    </div>
                </div>
        </aside>
        </div>
    </div>
</section>

{% endblock %}