src/accounts/urls.py
from django.urls import path

from accounts.views import (
    UserRegistrationView,
    UserLoginView,
    UserLogoutView,
    UserActivationView,
    UserDashboardView,
    UserForgotPassword, UserResetValidateView, UserResetPassword, UserDashboardOrdersView, UserDashboardChangeProfile,
    UserDashboardChangePassword, UserDashboardOrderDetails
)

app_name = 'accounts'

urlpatterns = [
    path('accounts/register/', UserRegistrationView.as_view(), name='register'),
    path('accounts/login/', UserLoginView.as_view(), name='login'),
    path('accounts/logout/', UserLogoutView.as_view(), name='logout'),
    
    path('accounts/dashboard/', UserDashboardView.as_view(), name='dashboard'),
    path('accounts/dashboard/orders/', UserDashboardOrdersView.as_view(), name='dashboard_orders'),
    path('accounts/dashboard/order/<int:pk>/details/', UserDashboardOrderDetails.as_view(), name='order_details'),
    path('accounts/dashboard/profile/', UserDashboardChangeProfile.as_view(), name='dashboard_profile'),
    path('accounts/dashboard/password/', UserDashboardChangePassword.as_view(), name='dashboard_password'),
    
    path('accounts/activate/<uidb64>/<token>', UserActivationView.as_view(), name='activation'),
    
    path('accounts/forgot_password/', UserForgotPassword.as_view(), name='forgot_password'),
    path('accounts/reset_password_validate/<uidb64>/<token>', UserResetValidateView.as_view(), name='reset_password_validate'),
    path('accounts/reset_password/', UserResetPassword.as_view(), name='reset_password'),
]

src/cart/urls.py
from django.urls import path

from cart.views import CartAddView, CartIndex, CartDeleteView, CartItemRemoveView, CheckoutView

app_name = 'cart'

urlpatterns = [
    path('cart/', CartIndex.as_view(), name='index'),
    path('cart/add/<int:id>', CartAddView.as_view(), name='add'),
    path('cart/reduce/<int:product_id>/<int:cart_item_id>', CartDeleteView.as_view(), name='reduce'),
    path('cart/remove/<int:id>', CartItemRemoveView.as_view(), name='remove'),
    path('cart/checkout/', CartIndex.as_view(template_name='checkout.html'), name="checkout")
]

src/ecommerce/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings
from .views import home

from django.contrib.auth import get_user_model, login
from django.http import HttpResponse


urlpatterns = [
        path('secure_admin/', admin.site.urls),
        path('', home, name='home'),
        path('', include('store.urls')),
        path('', include('cart.urls')),
        path('', include('accounts.urls')),
        path('', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/store/urls.py
from django.urls import path

from store.views import ProductsList, ProductDetails

app_name = 'store'

urlpatterns = [
    path('store/', ProductsList.as_view(), name='index'),
    path('store/category/<slug:slug>/', ProductsList.as_view(), name='index'),
    path('store/details/<slug:slug>/', ProductDetails.as_view(), name='product-details'),
    path('store/search/', ProductsList.as_view(), name='search'),
]

src/templates/includes/dashboard_sidebar.html
<aside class="col-md-3">
    <ul class="list-group">
        <a class="list-group-item {% if request.path == '/accounts/dashboard/' %}active{% endif %}" href="{% url 'accounts:dashboard' %}">Dashboard</a>
        <a class="list-group-item {% if '/orders/' in request.path  %}active{% endif %}" href="{% url 'accounts:dashboard_orders' %}">commandes</a>
        <a class="list-group-item {% if '/profile/' in request.path  %}active{% endif %}" href="{% url 'accounts:dashboard_profile' %}">Modifier le profile</a>
        <a class="list-group-item {% if '/password/' in request.path  %}active{% endif %}" href="{% url 'accounts:dashboard_password' %}">Changer le mot de passe</a>
    </ul>
    <br>
    <form action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-light btn-block mb-5" type="submit"> <i class="fa fa-power-off"></i> <span class="text">Se déconnecter</span> </button>
    </form>
</aside>

src/templates/includes/footer.html
{% load static %}


<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-4">
				<p class="text-muted"> &copy 2025 KONGO Hermès Eliram</p>
			</div>
			<div class="col-md-6 text-md-center">
				<span  class="px-2">hermeskongo@gmail.com</span>
				<span  class="px-2">+212 0783535908</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

src/templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
            <div class="text-center alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {% for message in messages %} {{ message }} {% endfor %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
    {% endfor %}
    <script>
        setTimeout(function() {
            $('.alert').fadeOut('slow')
        }, 4500);
    </script>
{% endif %}

src/templates/includes/navbar.html
{% load static %}
<header class="section-header">
<nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
<div class="container">
    {% if user.is_authenticated %}
      <ul class="navbar-nav p-2 mx-auto d-flex align-items-center">
          <p>Bienvenue <strong>{{ user.first_name|capfirst }}</strong></p>
      </ul>
        <span class="nav-item">
          <a href="{% url 'accounts:dashboard' %}" class="nav-link text-primary">Dashboard</a>
        </span>
    {% endif %}

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTop4">
    <ul class="ml-auto navbar-nav">
		<li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
		<li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
	</ul> <!-- list-inline //  -->
  </div> <!-- navbar-collapse .// -->
</div> <!-- container //  -->
</nav>

<section class=" border-bottom">
	<div class="p-3">
<div class="row align-items-center">
	<div class="col-lg-1 col-md-3 col-6">
		<a href="{% url 'home' %}" class="brand-wrap">
			<img class="logo" style="width: 100%" src="{% static './images/logo.png' %}">
		</a> <!-- brand-wrap.// -->
	</div>
	<div class="col-lg-2 col-sm col-md col-6 flex-grow-0">
		<div class="category-wrap dropdown d-inline-block float-right">
			<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
				<i class="fa fa-bars"></i> Carégories
			</button>
			<div class="dropdown-menu">
                    <a href="{% url 'store:index' %}" class="dropdown-item">Tout</a></a>
                {% for category in categories %}
                    <a href="{% url 'store:index' slug=category.slug %}" class="dropdown-item">{{ category.name }}</a></a>
			    {% endfor %}
            </div>
		</div>  <!-- category-wrap.// -->
	</div> <!-- col.// -->
    <a href="{% url 'store:index' %}" class="btn btn-outline-primary">Boutique</a>
	<div class="col-lg-5 col-md-6 col-sm-12 col">
		<form action="{% url 'store:search' %}" class="search" method="get">
			<div class="input-group w-100">
			    <input type="text" class="form-control" style="width:60%;" placeholder="Rechercher" value="{{ request.GET.keyword }}" name="keyword">

			    <div class="input-group-append">
			      <button class="btn btn-primary" type="submit">
			        <i class="fa fa-search"></i>
			      </button>
			    </div>
		    </div>
		</form> <!-- search-wrap .end// -->
	</div> <!-- col.// -->
            {% if not user.is_authenticated %}
             <div class="col-lg-2 col-md-4 col-sm-12 my-sm-4" >
                <div class="ml-5 d-block">
                    <a href="{% url 'accounts:login' %}">Se connecter</a> <span class="dark-transp"> | </span>
                    <a href="{% url 'accounts:register' %}">S'inscrire</a>
                </div>
            </div>
            {% else %}
             <div class="col-lg-2 col-md-4 col-sm-12 my-sm-4" >
                <form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-primary" type="submit">Se déconnecter</button>
                </form>
             </div>
            {% endif %}
	<div class="col-lg-1 col-sm-4 col-2">
				<div class="d-flex mb-3 mb-lg-0 align-items-center justify-content-between">
					<a href="{% url 'cart:index' %}" class="widget-header d-block" style="margin-left: -5%">
						<div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
						<span class="badge badge-pill badge-danger notify">{{ cart_counter }}</span>
					</a>
				</div>
			</div> <!-- col.// -->
</div> <!-- row.// -->
	</div> <!-- container.// -->
</section> <!-- header-main .// -->




</header> <!-- section-header.// -->